### ISSUE TITLE
friendship

### ISSUE THREAD

**Issue by meandavejustice** [contra/windows_98.css#8]
I need to talk 2 u about *Buenvenidos a Miami* dm me this week plz :kissing_heart:

**Comment by jden** [comment]
how do i open a PR on an Issue (cc @jlord) cause someone gotta s/buenvenidos/bienvenido/ that shi

**Comment by meandavejustice** [comment]
i just copied it from azlyrics, you may want to open it upstream. @jden

**Comment by jlord** [comment]
I think a PR on an Issue is still just a PR :grin: throw in a cross reference for good measure of course.

**Comment by contra** [comment]
delete my number never contact me again
